### ISSUE TITLE
Issue with testPerformUpkeepRevertsIfCheckUpkeepIsFalse()

### ISSUE THREAD

**Issue by dannweeeee** [Cyfrin/foundry-smart-contract-lottery-f23#29]
<img width="816" alt="Screenshot 2023-09-14 at 1 01 56 AM" src="https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/42776950/4ee48c62-3516-4b76-8944-d9a4cb8a12db">

when I forge test, all tests seems to work, but when I forge test --fork-url $SEPOLIA_RPC_URL, it gave this error. I understand that the error is because the currentBalance is 4e16 but it should be zero.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by usgeeus** [comment]
@dannweeeee  @PatrickAlphaC 
The raffle contract gets deployed to address '0xA8452Ec99ce0C64f20701dB7dD3abDb607c00496'.
and there is 0.04 ETH (40000000000000000 wei) on that address. See this [etherscan](https://sepolia.etherscan.io/address/0xA8452Ec99ce0C64f20701dB7dD3abDb607c00496) 
That's why that test function fails.
So you'll need to add below to the constructor function.
```
payable(msg.sender).transfer(address(this).balance);
```

You can fix the test function without fixing the constructor function, as shown below, but it's not recommended.
```
    function testPerformUpkeepRevertsIfCheckUpkeepIsFalse() public {
        // Arrange
        uint256 currentBalance = address(raffle).balance;
        uint256 numPlayers = 0;
        uint256 raffleState = 0;
        // Act / Assert
        vm.expectRevert(
            abi.encodeWithSelector(
                Raffle.Raffle__UpkeepNotNeeded.selector,
                currentBalance,
                numPlayers,
                raffleState
            )
        );
        raffle.performUpkeep("");
    }
```
